version: '3.1'

services:

  mongo:
    image: mongo
    command: 'mongod --clusterAuthMode x509 --sslMode requireSSL --sslPEMKeyFile /data/db/cert/server.pem --sslCAFile /data/db/cert/rootCA.pem'
    volumes:
      - './mongo-data:/data/db'
    restart: always
    networks: 
      - net_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  

networks:
  net_mongo:
    driver: bridge